"""add_exercise_log

Revision ID: 3604915943af
Revises: d62d3df7be68
Create Date: 2026-04-23 13:36:50.820963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3604915943af'
down_revision: Union[str, None] = 'd62d3df7be68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercise_log',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.String(length=50), nullable=False),
    sa.Column('skill_id', sa.String(length=50), nullable=False),
    sa.Column('exercise_type', sa.String(length=30), nullable=False),
    sa.Column('variant', sa.Integer(), nullable=False),
    sa.Column('correct', sa.Boolean(), nullable=False),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('hint_used', sa.Boolean(), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exercise_log_created_at'), 'exercise_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_exercise_log_lesson_id'), 'exercise_log', ['lesson_id'], unique=False)
    op.create_index(op.f('ix_exercise_log_skill_id'), 'exercise_log', ['skill_id'], unique=False)
    op.create_index(op.f('ix_exercise_log_user_id'), 'exercise_log', ['user_id'], unique=False)
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'student'::character varying"))
    op.alter_column('users', 'permissions',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'[]'::json"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'permissions',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'[]'::json"))
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'student'::character varying"))
    op.drop_index(op.f('ix_exercise_log_user_id'), table_name='exercise_log')
    op.drop_index(op.f('ix_exercise_log_skill_id'), table_name='exercise_log')
    op.drop_index(op.f('ix_exercise_log_lesson_id'), table_name='exercise_log')
    op.drop_index(op.f('ix_exercise_log_created_at'), table_name='exercise_log')
    op.drop_table('exercise_log')
    # ### end Alembic commands ###
