"""add degree and degree_name to modules

Revision ID: 6955911fceb7
Revises: 7da3b1ccb357
Create Date: 2026-04-27 12:09:58.334911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6955911fceb7'
down_revision: Union[str, None] = '7da3b1ccb357'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('modules', sa.Column('degree', sa.Integer(), nullable=False, server_default='1'))
    op.add_column('modules', sa.Column('degree_name', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('modules', 'degree_name')
    op.drop_column('modules', 'degree')
    # ### end Alembic commands ###
