"""add_oral_quota_fields

Revision ID: bed109113c7a
Revises: ca29dc874f29
Create Date: 2026-05-10 12:20:27.677395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bed109113c7a'
down_revision: Union[str, None] = 'ca29dc874f29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('oral_evaluations_this_month', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('users', sa.Column('oral_evaluations_reset_date', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'oral_evaluations_reset_date')
    op.drop_column('users', 'oral_evaluations_this_month')
    # ### end Alembic commands ###
